name: Generate VoIP List
on:
  schedule:
    - cron: '0 */6 * * *'  # cada 6 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run generator
        run: bash generate_voip_list.sh
      - name: Commit updated list
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add voip_videocall.rsc
          git commit -m "Auto-update VoIP list ($(date))" || echo "No changes"
          git push
